try

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -36,6 +36,8 @@ jobs:
         with:
           path: terraform/prod
       - name: test output
-        run: echo "${{ steps.tf-config-inspect.outputs.config}}" | jq -r -c .module_calls[].source | while read i; do if [[ $i = @("git@github.com:cahcommercial/outcomes-aws-ct-tf-module-ec2") ]]; then echo "found module"; else echo "module not found" && exit 1; fi; done;
+        run: | 
+          echo "${{ steps.tf-config-inspect.outputs.config}}" >> test.json
+          jq -r -c .module_calls[].source test.json | while read i; do if [[ $i = @("git@github.com:cahcommercial/outcomes-aws-ct-tf-module-ec2") ]]; then echo "found module"; else echo "module not found" && exit 1; fi; done;
       
         
