try

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -38,6 +38,6 @@ jobs:
         with:
           path: terraform/prod
       - name: test output
-        run: echo '${{ steps.tf-config-inspect.outputs.config }}' | jq -r -c .module_calls[].source test.json | while read i; do if [[ $i = @("git@github.com:cahcommercial/outcomes-aws-ct-tf-module-ec2|git@github.com:cahcommercial/outcomes-aws-ct-tf-module-sns") ]]; then echo "found module"; else echo "module not found" && exit 1; fi; done;
+        run: echo '${{ steps.tf-config-inspect.outputs.config }}' | jq -r -c .module_calls[].source | while read i; do if [[ $i = @("git@github.com:cahcommercial/outcomes-aws-ct-tf-module-ec2|git@github.com:cahcommercial/outcomes-aws-ct-tf-module-sns") ]]; then echo "found module"; else echo "module not found" && exit 1; fi; done;
       
         
